[package]
name = "Craft"
version = "0.1.0"
authors = ["Klaus Klein <klaus.klein@cwi.com.br>"]
includes = ["shaders", "textures"]


[dependencies]
sqlite3="3.32.2"
libcurl="7.71.1"
glew="2.1.0"
glfw="3.3.2"

[system_dependencies]
linux=["m","pthread","X11","dl","GL"]
windows=["Shell32","gdi32"]
